# services:
#   flow2api:
#     build: .
#     image: thesmallhancat/flow2api:latest
#     container_name: flow2api
#     ports:
#       - "38000:8000"
#     volumes:
#       - ./data:/app/data
#       - ./config/setting.toml:/app/config/setting.toml
#       - ./src:/app/src
#       - ./main.py:/app/main.py
#       - ./browser_data:/app/browser_data
#     environment:
#       - PYTHONUNBUFFERED=1
#       - DISPLAY=:99
#     restart: unless-stopped


